lib/Select.js
=> do not deselect option when user select the same option

README.md, src/Dropdown.jsx, src/Select.jsx
1. 增加 `props.dropdownClassName`。
默认 renderToBody 之后，想要自定义某个实例的浮层样式变得很困难。
有 `dropdownClassName` 就方便一些。
`dropdownStyle` `dropdownMenuStyle` 的问题是 style object 写起来太累，而且不好复用。
2. 给 dropdown 加上 single 和 multiple 的样式。因为单选和复选框的浮层样式有区别，原来 render 的方式可以从父节点进行区别，现在到 body 了需要额外加上。
=> Add dropdownClassName to dropdown

assets/index.less
修复单选选中项内容过长时，`text-overflow: ellipsis;` 不起作用问题
=> add white-space: nowrap

examples/combobox.js, src/DropdownMenu.jsx, src/SelectTrigger.jsx
当搜索建议模式时，选中某项之后，当前菜单的 active 状态不会清除。导致再次输入字符并回车时（原有的 options 不变的情况下），会重置回前面选中的值。
相关：https://github.com/react-component/menu/pull/26
=> clear active menu when combobox input change

src/SelectTrigger.jsx
始终添加 `min-width`，避免 `dropdownMatchWidth={false}` 时下图的问题：
=> Add min-width for select dropdown

README.md, src/Select.jsx
Close: https://github.com/ant-design/ant-design/issues/1917
=> Fix: click arrow should be no-op when disabled select

package.json, src/Select.jsx
- fix https://github.com/ant-design/ant-design/commit/3c9ccccf610d111bf491e2440bf75b25dfafe70b#commitcomment-19785395
=> fix header select bug

.babelrc, package.json, tests/Combobox.spec.js, tests/OptGroup.spec.js, tests/Select.spec.js, tests/__snapshots__/Select.spec.js.snap, tests/index.js, tests/optionFilterProp.spec.js, tests/tags.spec.js, tests/util.spec.js
mocha 迁移到 jest 只要调整下 expect 的写法，这里只转换了一部分，看看行不行。
运行：`npm run jest`
=> Introduce jest and enzyme

src/Select.jsx, tests/Select.combobox.spec.js
现在 combobox 设置 defaultValue 和第一次的 value 都不能正确显示为对应的  label。
=> Fix label displaying for initial value

src/Select.jsx
+ close https://github.com/ant-design/ant-design/issues/4576
+ 原因：this.mabeFocus 中，inputElement 的 focus 会再触发一次 onFocus
=>  Fix issue that onFocus will trigger twice

examples/multiple.js, src/Select.jsx, tests/Select.multiple.spec.js
+ close #https://github.com/ant-design/ant-design/issues/4808
+ 由于 multiple 和 tags 一类的 focus 行为不一致，所要额外判断一下。
=>  Fix onFocus of multiple select

src/Select.jsx, tests/Select.spec.js
碰到的问题是，在 input 为空的情况下选择一个选项，这时会同时触发 `onSelect` 和 `onSearch`，且 `onSearch` 得到的参数是个空字符串，这个 `onSearch` 是多余的。
=> Fire search event only when inputValue changes

src/PropTypes.js, src/Select.jsx, tests/Select.spec.js
Ref https://github.com/ant-design/ant-design/issues/3734 https://github.com/ant-design/ant-design/issues/5292
=> Improve value validate message

src/Select.jsx, tests/Select.spec.js
+ close https://github.com/ant-design/ant-design/issues/5487
=>  passThrough `onKeyDown` of Custom Input

tests/Select.combobox.spec.js, tests/Select.multiple.spec.js, tests/Select.spec.js, tests/Select.tags.spec.js, tests/__snapshots__/Select.combobox.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.tags.spec.js.snap, tests/shared/allowClearTest.js
ref: https://github.com/react-component/select/pull/172
=> test: add test for allowClear

src/util.js, tests/Select.multiple.spec.js, tests/util.spec.js
`Select[multipie || tags]` with `OptGroup` can reproduce
relervant: https://github.com/ant-design/ant-design/issues/5567
=> fix Select[multipie] with OptGroup will cause error.

examples/suggest.js, src/Select.jsx
+ ref https://github.com/ant-design/ant-design/issues/5601
+ getInputDOMNode cannot get correct input element, so `document.activeElement
=== this.getInputDOMNode())` will always false.
+ add scheme of `getInputElement`: if getInputElement returns an `React.Element`, the element must implemented `refs.input` to point to its real input element.
=>  Customize Input Element of Select bug

src/Select.jsx, tests/Select.spec.js
close ant-design/ant-design#5954
=> click placeholder should trigger onFocus

src/DropdownMenu.jsx, src/Select.jsx, tests/Select.spec.js
+ close https://github.com/ant-design/ant-design/issues/5741
+ close https://github.com/ant-design/ant-design/issues/5792
+ close https://github.com/ant-design/ant-design/issues/5778
There's a confusing `onFocus` flow:
Focus `<Select />`, onFocus trigger.
* `<Trigger/>` focus
* `<div />` focus, 
* `onOuterFocus()` => `props.onFocus()` // Select onFocus callback here
* `setPopupVisible()` =>`Trigger.onPopupVisibleChange()` => `setOpenState(true)`
* `<input />` get focus.
Focus `<input />`, onFocus not trigger
* `<Trigger />` focus
* `<input />` focus,
* `setPopupVisible()` =>`Trigger.onPopupVisibleChange()` => `setOpenState(true)`
* `<input /> ` already focus, do nothing.
=> Focus and blur issues

src/DropdownMenu.jsx, src/SelectTrigger.jsx
=> Migrate to ES6 syntax

src/FilterMixin.js, tests/FilterMixin.spec.js, tests/Select.spec.js, tests/__snapshots__/FilterMixin.spec.js.snap, tests/util.spec.js
I discovered this issue when using ant-design. Since Ant-Design defaults filterOption to false I needed to pass set filterOption to true. When I did that I discovered that no options were being filtered. Here is a [codepen](https://codepen.io/gklinsing/pen/MooJJZ) showing this.
I tracked the problem line down to [FilterMixin.js#L16](https://github.com/react-component/select/blob/master/src/FilterMixin.js#L16). When you pass in true it doesn't use defaultFilter, but rather returns true for each option.
=> Passing true to "filterOption" will return all options instead of those matching input

src/Select.jsx, tests/Select.combobox.spec.js, tests/__mocks__/rc-trigger.js
close https://github.com/ant-design/ant-design/issues/6600
=> Fix reopen combobox

examples/single.js, src/Select.jsx
to solve this https://github.com/ant-design/ant-design/issues/6318
=> add afterDropdownVisibleChange

src/Select.jsx, tests/Select.spec.js
close ant-design/ant-design#6342
=> Close panel when blur select

README.md, examples/combobox.js, examples/single.js, package.json, src/DropdownMenu.jsx, src/Select.jsx, tests/Select.combobox.spec.js, tests/Select.spec.js
Close https://github.com/ant-design/ant-design/issues/5764
=> Add backfill

src/Option.jsx, src/PropTypes.js, src/Select.jsx, src/util.js, tests/Select.combobox.spec.js, tests/Select.multiple.spec.js, tests/Select.spec.js, tests/Select.tags.spec.js, tests/shared/throwOptionValue.js
#228
Close #115 https://github.com/ant-design/ant-design/issues/2857
=> Support number value

src/Select.jsx, tests/Select.combobox.spec.js, tests/Select.spec.js, tests/__snapshots__/Select.combobox.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.spec.js.snap, tests/__snapshots__/Select.tags.spec.js.snap
=> Fix clear icon of combobox select

src/Select.jsx
When having to select more than 100 options, all those tags become a performance issue. It's better to be able to treat the Select as a normal multiple select input, limiting the amount of selected tags:
=> Add limit to the amount of selected tags shown

src/PropTypes.js, src/Select.jsx, tests/Select.multiple.spec.js, tests/Select.tags.spec.js, tests/shared/hoverTest.js
=> Propagate onMouseEnter and onMouseLeave from SelectTrigger to Select

src/util.js, tests/util.spec.js
Hello,
I found this issue because of this component's usage in AntDesign. There was actually another issue filed there for a very similar problem that was already fixed in this repo: https://github.com/ant-design/ant-design/issues/5831
What I found is that, if I paste in input that contains multiple separators *followed by valid input*, it crashes their Select component. I traced it back to here.
In the fix provided for https://github.com/ant-design/ant-design/issues/5831 in  https://github.com/react-component/select/commit/b4c7c3e2de7286df33366832c9676e6f8fc1823a, the solution effectively implements `String.prototype.trim` on the array representing the string - i.e. empty elements at the beginning and the end of the array will be trimmed off.
What this solution did not account for is …
=> Fix Multiple Repeating Separators Issue

src/Select.jsx, tests/setup.js
fixed #241 
Should use `React.Children` to traverse the children of a react element. Now that there is a common utility is capable of achieving this, use it instead:
https://github.com/react-component/util/blob/8d5c97fadfd353c75ec058ec310c76ed530f733b/src/Children/toArray.js#L3
BTW, I added the missing name of mock function `requestAnimationFrame` which causes the warning of lint.
=> fix: the children should traversed by using standard api `React.Children`

examples/tags.js, src/Select.jsx, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.tags.spec.js.snap, tests/shared/renderTest.js
allow maxTagCount to be 0, for some scenes like
=> fix: tag display correct when maxTagCount value is 0

src/util.js, tests/Select.spec.js
The default filter works not properly when children is an array.
=> Fix defaultFilter can not filter array children

examples/multiple.js, examples/optgroup.js, src/DropdownMenu.jsx, src/Select.jsx, src/SelectTrigger.jsx, src/util.js, tests/DropdownMenu.spec.js, tests/Select.combobox.spec.js, tests/Select.multiple.spec.js, tests/Select.spec.js, tests/Select.tags.spec.js, tests/shared/dynamicChildrenTest.js, tests/shared/removeSelectedTest.js
And fix https://github.com/ant-design/ant-design/issues/9445
old `state.value`: `[{ key: xxx, label: xxx, title: xxx }]` => new `state.value` : `[ 'xxx', 'xxx' ]`.
state.value only store key. label, title and Option store in optionsInfo.
=> refactoring: update state.value format

src/DropdownMenu.jsx, src/Select.jsx, src/util.js, tests/__snapshots__/Select.combobox.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.spec.js.snap, tests/__snapshots__/Select.tags.spec.js.snap
https://github.com/ant-design/ant-design/issues/10095
before:
after:
(weird that there are no incidents of aria-* error but still print an empty list) 
also: value of unselectable should be `on` or `off`
https://stackoverflow.com/questions/69430/is-there-a-way-to-make-text-unselectable-on-an-html-page (could not find an official doc...)
=> chore: fix aria-* attributes

src/Select.jsx
Test case already in `Select.spec.js > 'close after select'`. No need additional test case.
ref: https://github.com/ant-design/ant-design/issues/10400
=> fix 'react-lifecycles-compat' affect in react 16.2.0

src/Select.jsx, tests/Select.multiple.spec.js
* 用回车键选中并不会触发onSubmit
* 支持用回车键取消选中
=> Prevent form onSubmit events

src/DropdownMenu.jsx, tests/__snapshots__/DropdownMenu.spec.js.snap, tests/__snapshots__/Select.spec.js.snap, tests/__snapshots__/Select.tags.spec.js.snap
This commit will resolve a known scrolling performance issue related to scrollable areas.
The thing is that scrolling force repaints (draw the UI pixels) whenever the user is scrolling,
and that causes a lot of repaints that could be avoided using GPU accelerated repaints.
For legacy fix I'm using transform: translateZ(0) which will give the GPU to handle those repaints which make
the scrolling performance more better
Affected pages among the examples with this issue:
- http://react-component.github.io/select/examples/tags.html
- http://react-component.github.io/select/examples/single.html
- http://react-component.github.io/select/examples/multiple.html
Inspect the Chrome "rendering" tab in Devtools to validate the issue.
I'll be attaching a screenshots for the reproduction
=> [enhancement] - Scrolling performance issues

README.md, examples/custom-icon.js, src/DropdownMenu.jsx, src/PropTypes.js, src/Select.jsx, src/SelectTrigger.jsx
暴露 `menuItemIcon` 接口供 `antd` 使用。用于解决下面的问题：
期望：
=> Support Menu Item Icon suffix

examples/combobox.js, examples/suggest.js, examples/tags.js, src/Select.jsx
修复 https://github.com/react-component/select/pull/327 导致的single、combobox模式下focus触发异常的问题。
这个问题的原因是
多选的情况下，onFocus是直接在onDropdownVisibleChange事件里调用的。
而在单选情况下，鼠标按下时就会触发focus事件，这个时候onOuterFocus里调用onFocus的代码被上次的提交里加的_mouseDown判断拦截了，因为这个时候已经focus了，所以在onDropdownVisibleChange里不会再调用onFocus了。这次的pr主要就是绕过单选模式下onOuterFocus里的_mouseDown判断，因为本质上是没必要的。
ps: _mouseDown是在上面pr里防止点击select多次触发focus的flag。
=> bugfix: focus not work in single mode

src/Select.jsx
This solves the bug where one can't enter SPACE while searching for options in single mode. Ref #333
=> adding spaces on search in single mode

src/Select.jsx
A bad input value would be result in an undefined calculated value.
Validating an undefined value could empty the select control.
So when losing focus from a multiple select which already has some values,
the select would be emptied.
a bad input value should not be update the value to be validated.
=> only update value with a good input value

src/Select.tsx
- Fix https://github.com/ant-design/ant-design/issues/14220
This issue caused because `getValueByInput` return wrong result in `onOuterBlur`. The root cause is `getValueByLabel` does not filter the _disabled_ options. So I added a filter in that function.
It seemed works well.
=> Fix disabled option bug in multiple search mode

now.json, package.json, src/Select.tsx, tests/Select.spec.tsx
fix https://github.com/ant-design/ant-design/issues/16377
ref: https://github.com/ant-design/ant-design/pull/16235#issuecomment-487506523
-----------------
hot fix：
内部有几个分支会触发 search change，这里给 `setOpenState` 额外添加了一个参数用于处理 select 时不要触发 onSearch。
将来需要重构将 inputChange 逻辑从 popup 开关里抽出来。
=> fix: Don't trigger onSearch when option is selected

package.json, src/Select.tsx, tests/Select.combobox.spec.tsx
修复比较恶心，Select 本身不管 Menu 里的状态，如果要判断是否当前有 active 的选项需要扒 Menu 的 mini-store 里的值。
为了不要这么耦合，折中选取 combobox 模式下且 defaultActive 为 false 时，按了 enter 后自动关闭 popup，以使得行为可以透传出来。
fix https://github.com/ant-design/ant-design/issues/16572
=> fix: delay to close in combobox

package.json, src/SelectTrigger.tsx, typings/index.d.ts
> 1. 针对使用antd表格，在大量数据下的调优
> 2. 表格下的分页使用了该控件，存在forced reflow的问题
> 将获取offsetwidth的行为放置requestAnimationFrame中
```
const raf = window.requestAnimationFrame
|| window.webkitRequestAnimationFrame
|| window.mozRequestAnimationFrame
|| window.msRequestAnimationFrame
|| function(cb) { return setTimeout(cb, 16); };
function componentDidMount() {
raf(this.setDropdownWidth);
}
function componentDidUpdate() {
raf(this.setDropdownWidth);
}
```
> 无明显影响
> 性能优化，将获取offsetwidth的行为放置requestAnimationFrame中
无
=> 性能调优，将获取offsetwidth的行为放置requestAnimationFrame中

src/Select.tsx, tests/Select.spec.tsx
close https://github.com/ant-design/ant-design/issues/17843
=> fix: `onSelect` should keep trigger

src/utils/valueUtil.ts, tests/Combobox.test.tsx, tests/Select.test.tsx, tests/Tags.test.tsx, tests/shared/dynamicChildrenTest.tsx
Follow code will work after this PR:
```jsx
<Select filterOption={(input, option) => option.props.children.includes(input)} />
```
=> feat: Support legacy `props` param with warning

.eslintrc.js, README.md, package.json, src/SelectTrigger.tsx, src/Selector/index.tsx, src/generate.tsx, src/interface/index.ts, tests/__snapshots__/Select.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
https://rc-select-git-new-trigger.react-component.now.sh/iframe.html?selectedKind=rc-select&selectedStory=single-animation
新的方式会尝试查找 ref 是否为 DOM，或者降级为 `findDOMNode` 但是导致了对 Function Component 无能为力，只能临时提供一个 `geDOMNode` 来索引真实的 DOM。感觉改造成本略大。
=> chore: Update rc-trigger

src/Option.tsx, src/interface/index.ts
Due to the mix of `Omit` and `keyof` for mapped type, the type declaration of `OptionProps` in current beta version(10.x) fails to work expectedly.
Try to explain this.
```ts
// declaration of Typescript's built-in `Omit` utility
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```
```ts
interface Foo {
bar: string;
baz: number;
[key: string]: any;
}
type FooKey = keyof Foo; // string | number
type FooKeyExclude = Exclude<FooKey, 'bar'>; // string | number
/**
* `FooOmit` will be
* ```ts
* {
*   [x: string]: any;
*   [x: number]: any;
* }
* ```
*/
type FooOmit = Pick<Foo, FooKeyExclude>;
```
The `OptionProps` of current version ships with the same fault.
```ts
// path: `$PROJECT_ROOT/src/interface/index.ts`
export interface OptionData {
/* some properties ... */
/** Save …
```
=> fix: Typescript type declaration of OptionProps

.gitignore, .prettierrc, src/generate.tsx, tests/Select.test.tsx
Hide popup when `notFoundContent` is `null` & `list` is empty.
ref: https://github.com/ant-design/ant-design/issues/19889
=> chore: No popup when null empty

examples/combobox.tsx, src/generate.tsx, tests/Combobox.test.tsx
fix https://github.com/ant-design/ant-design/issues/21018
=> fix: AutoComplete mode should support value control of `searchValue`

src/generate.tsx, tests/__snapshots__/Tags.test.tsx.snap
This fix a performance issue when components are update asynchronously
resolves: https://github.com/ant-design/ant-design/issues/21210
=> improve performance, don't read offsetWidth when popup is not shown

examples/auto-adjust-dropdown.tsx, src/SelectTrigger.tsx, tests/Select.test.tsx
Originally, when dropdownMatchSelectWidth is not provided and the width of the dropdown is larger than the width of the Select input, the dropdown will overflow instead of adjusting position automatically. This change checks dropdownMatchSelectWidth changes the dropdown placement overflow.adjustX accordingly
=> Auto-adjust dropdown horizontally when dropdownMatchSelectWidth is false

src/Selector/SingleSelector.tsx, tests/Combobox.test.tsx
Ref: https://github.com/react-component/select/pull/459
Resolve https://github.com/ant-design/ant-design/issues/22093
=> fix: null value display when mode is combobox

src/OptionList.tsx, tests/OptionList.test.tsx
Resolve https://github.com/ant-design/ant-design/issues/22162
=> fix: set data attributes

src/Selector/MultipleSelector.tsx, src/Selector/SingleSelector.tsx, tests/Multiple.test.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/22250
=> fix: Select placeholder disappear when searchValue controlled

src/OptionList.tsx, src/Selector/Input.tsx, src/Selector/index.tsx
fix https://github.com/ant-design/ant-design/issues/22268
又是一个 enzyme 不能 mock 的情况，好烦。只能加个备注了。
=> fix: AutoComplete typing to open input value

src/Selector/index.tsx, tests/Multiple.test.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/22736
=> Fix selection trigger open logic

README.md
`firstActiveValue` has been deprecated.
=> remove firstActiveValue

src/OptionList.tsx, src/generate.tsx
Clear all timeouts when unmounting the select component to avoid errors on runtime and when testing.
Fix https://github.com/ant-design/ant-design/issues/23093 as described by @afc163 in https://github.com/ant-design/ant-design/issues/23093#issuecomment-612415036
=> Clear timeouts when unmounting

package.json, src/generate.tsx, src/hooks/useCacheDisplayValue.ts, tests/Select.test.tsx
resolve https://github.com/ant-design/ant-design/issues/23996
旧版的 Select 状态同步有些问题，使得 options 移除但 value 不变时 label 没有刷掉。感觉是个不错的 “feature”，加一个 cache 来实现这个效果。
=> chore: Cache display label

src/Selector/Input.tsx, tests/__snapshots__/Multiple.test.tsx.snap, tests/__snapshots__/Select.test.tsx.snap
add `readonly` compatibility for IE11 [#24034](https://github.com/ant-design/ant-design/issues/24034)
=> fix(#24034): add `readonly` compatibility for IE11

src/generate.tsx, src/hooks/useCacheOptions.ts, src/interface/generator.ts, src/utils/commonUtil.ts, src/utils/valueUtil.ts
[#22822](https://github.com/ant-design/ant-design/issues/22822)
=> chore: optimize multiple  onChange performence

src/Selector/Input.tsx, src/Selector/MultipleSelector.tsx, src/Selector/SingleSelector.tsx, src/Selector/index.tsx, src/generate.tsx, tests/Multiple.test.tsx, tests/Tags.test.tsx
not seperating words while compositing
输入法输入时候不分词
=> fix: not seperating words while compositing

src/generate.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/25057
=> fix: null should show options

examples/tags.tsx, index.js, src/Selector/MultipleSelector.tsx, src/Selector/index.tsx, src/generate.tsx, tests/Multiple.test.tsx, tests/Tags.test.tsx
fix https://github.com/ant-design/ant-design/issues/23639
=> fix: can't separate input when mode=tags and open=false

src/Selector/SingleSelector.tsx, tests/Combobox.test.tsx
fix https://github.com/ant-design/ant-design/issues/25345
=> fix single backfill logic

src/Selector/index.tsx, src/generate.tsx
fix https://github.com/ant-design/ant-design/issues/25228
close https://github.com/react-component/select/pull/514
=> fix: Paste logic

src/generate.tsx, tests/Tags.test.tsx
- When using `mode=tags`, it search values based on `optionFilterProp` value. However, Even If the option which has the same `optionFilterProp` value, `mode=tags` unshift new option to `displayOptions`.
- For now, it checks values between `option.value` and `mergedSearchValue` to decide whether it unshift new option or not
- I think that the condition should be changed to use `optionFilterProp`.
=> feat: Update Tags Mode to display options matched with optionFilterProp

src/Selector/index.tsx
close [#26648](https://github.com/ant-design/ant-design/issues/26648)
@afc163 
发现是这次提交导致的问题：https://github.com/react-component/select/commit/ed63549d8cef1e728057b7a55ecabaf61fff7b96
我看你把 focus 从 `onClick` 挪到了 `onMouseDown` 中，这导致在 IOS 上无法正常聚焦调起键盘，我又放回在 `onClick` 中了，你看看有什么问题？
=> fix: Keyboard not showing up on iOS when focus

examples/single.tsx, src/Selector/SingleSelector.tsx, tests/Select.test.tsx, tests/__snapshots__/Select.test.tsx.snap
https://github.com/ant-design/ant-design/issues/26790
=> fix: Search focus lost compositing status

src/OptionList.tsx, src/generate.tsx, src/interface/index.ts, tests/Combobox.test.tsx, tests/OptionList.test.tsx
resolve https://github.com/ant-design/ant-design/issues/26773
=> fix: backfill should not affected by mouse

src/Selector/MultipleSelector.tsx, tests/Tags.test.tsx, tests/shared/removeSelectedTest.tsx
resolve https://github.com/ant-design/ant-design/issues/27034
=> refactor: no closable when disabled

examples/combobox.tsx, src/Selector/Input.tsx, src/Selector/SingleSelector.tsx, src/Selector/index.tsx, src/generate.tsx, tests/Combobox.test.tsx
resolve https://github.com/ant-design/ant-design/issues/27954
=> feat: Combobox support max length

src/generate.tsx, tests/Multiple.test.tsx, tests/Select.test.tsx, tests/Tags.test.tsx
=> Fix for `tabIndex` prop handling

src/generate.tsx
about [#27964](https://github.com/ant-design/ant-design/issues/27964)
=> fix:tabindex prop will be set only on input element

assets/index.less, examples/tags.tsx, package.json, src/Selector/MultipleSelector.tsx, src/Selector/index.tsx, src/generate.tsx, src/interface/generator.ts, tests/__snapshots__/Multiple.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
动态测量依赖于元素尺寸，移除了节点动画。帮忙测测。另外，动态元素后，inline 对齐可能会有问题，之后如果用户有问题，就直接推荐用 Space。
https://select-git-responsive.react-component.vercel.app/?path=/story/rc-select--tags
第一个例子
(没问题再补测试)
=> feat: `maxTagCount="responsive"`

src/hooks/useCacheDisplayValue.ts, src/interface/generator.ts, src/utils/valueUtil.ts, tests/Select.test.tsx
Fix ant-design/ant-design#28495, if `item.value === item.label` in options, the true label will be replaced by `cacheLabel`. Add `isCacheable` may help fix this.
=> fix: correct update option's label when update value (equal label) in options

src/Selector/MultipleSelector.tsx, tests/Multiple.test.tsx, tests/Tags.test.tsx
https://github.com/ant-design/ant-design/issues/28449
=> fix: select TagRender Property not open dropdown when click

src/Selector/index.tsx, src/generate.tsx
将 `scrollTo` 能力暴露出来
相关 issue：
https://github.com/ant-design/ant-design/issues/24240
相关 PR：
https://github.com/react-component/tree-select/pull/298
=> feat: mount scrollTo on ref

src/Selector/index.tsx, tests/Tags.test.tsx
fix https://github.com/ant-design/ant-design/issues/28564
=> fix: Compositing should trigger again when ended

src/generate.tsx, src/hooks/useCacheOptions.ts, src/interface/generator.ts, src/utils/commonUtil.ts, src/utils/valueUtil.ts
fix https://github.com/react-component/select/issues/564
修改了 `getLabeledValue` 里面的 `find` 改为了 `Map` 获取。
**影响范围：**
getLabeledValue 的 `prevValue` 改为了 `prevValueMap`
toInnerValue 返回值 变成了两个参数 `[RawValueType[], Map<RawValueType, LabelValueType>]`
toOuterValues 的 `prevValue` 改为了 `prevValueMap`
@zombieJ 看看其他组件有没有用到，有没有什么影响？
=> chore: optimize search performance

src/OptionList.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/28815
当下拉列表打开时，退出键应该停止冒泡。
=> fix: should stopPropagation when pressing esc

src/Selector/index.tsx, tests/Tags.test.tsx
fix https://github.com/ant-design/ant-design/issues/28873
=> fix: breakline of seprator

src/hooks/useSelectTriggerControl.ts
fix for issue: https://github.com/ant-design/ant-design/issues/27250
=> fix: can not open in web component

examples/custom-icon.tsx, src/Selector/index.tsx, src/generate.tsx, tests/Combobox.test.tsx, tsconfig.json
resolve https://github.com/ant-design/ant-design/issues/29101
=> fix: Should not trigger onChange multiple times

src/generate.tsx
fixed the problem of generating empty tags by pressing Enter when nothing was entered.
Link issue: [`<Select />` in tags mode renders empty tag after pressing enter](https://github.com/ant-design/ant-design/issues/29493)
Solution: If the content is empty, return directly.
=> fix: press the Enter button and an empty tag may appear

src/generate.tsx
Closes: https://github.com/react-component/select/issues/521
In our project we encountered a similar problem problem as described in issue 521
In the PR I added a mobile check and a check if we have current in the `selectorRef`
=> added mobile check on the focus after blur event

src/Selector/MultipleSelector.tsx, tests/Tags.test.tsx
fixes https://github.com/ant-design/ant-design/issues/30220
continuation of https://github.com/react-component/select/pull/582
closes dropdown when it is open when clicking a custom TagRender prop
=> fix: select TagRender prop does not close dropdown when clicked when dropdown is open

src/generate.tsx, src/hooks/useSelectTriggerControl.ts
Pure render popup without state update will get empty list since popup is not ready yet.
=> fix: pure render should also check latest popup element

src/Selector/MultipleSelector.tsx, tests/Multiple.test.tsx, tests/__snapshots__/Multiple.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
=> feat: add title for tag in multiple mode (#636)

examples/singleFieldNames.tsx, src/OptionList.tsx, src/generate.tsx, src/hooks/useCacheOptions.ts, src/interface/generator.ts, src/interface/index.ts, src/utils/valueUtil.ts, tests/Field.test.tsx
感觉上游 `rc-tree-select` 还是需要锁一下版本，否则这种 breaking 改动不好处理。准备发个大版本之后全部锁 minor。
另外，和 @PeachScript 聊了一下 mono repo 改造成本略大，issue 和 PR 也需要迁移。可以走 git 子模块形式，但是需要自己搞一个版本依赖管理的东东。晚点我再研究研究。
ref https://github.com/ant-design/ant-design/issues/24282
=> feat: Support `fieldNames`

src/OptionList.tsx, src/utils/__mocks__/platformUtil.ts, src/utils/platformUtil.ts, tests/OptionList.test.tsx
Use <kbd>ctrl + n / p</kbd> to select list items. Closing https://github.com/ant-design/ant-design/issues/31641.
=> feat: support ctrl n/p on mac

src/OptionList.tsx, tests/Accessibility.test.tsx
resolve https://github.com/ant-design/ant-design/issues/31850
=> fix: Do not sync invalidate active index

package.json, src/SelectTrigger.tsx, src/generate.tsx, tests/Select.test.tsx, tests/SelectTrigger.spec.tsx
ref https://github.com/ant-design/ant-design/issues/32127
=> feat: Support placement

.eslintrc.js, .gitignore, src/generate.tsx, tests/Select.test.tsx, tests/focus.test.tsx
resolve https://github.com/ant-design/ant-design/issues/32753
=> fix: Disabled select should reset focus state

src/Selector/MultipleSelector.tsx, tests/__snapshots__/Multiple.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
resolve https://github.com/ant-design/ant-design/issues/32941
=> fix: maxTagTextLength should not cut label content

src/Selector/SingleSelector.tsx, src/index.ts, tests/Select.test.tsx, tests/__snapshots__/Select.test.tsx.snap
https://github.com/ant-design/ant-design/issues/27688
=> fix: select placeholder position

src/Select.tsx, tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/33495
=> fix: dropdownMatchSelectWidth={false} not disable virtual

src/Selector/SingleSelector.tsx, tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/33599﻿
=> fix: hide placehoder if showSearch and closed

assets/index.less, docs/examples/single-animation.tsx, src/Select.tsx, src/SelectTrigger.tsx, tests/Select.test.tsx
ref:
* https://github.com/ant-design/ant-design/issues/33273
* https://github.com/react-component/select/pull/687
* https://github.com/C-Hess/select/commit/71e978917170c1b765fd43a36b44f87165cd09fe
发现是个远古 BUG，`adjustX` 为 0 希望如果超出就自动切换。但是在 [`dom-align`](https://github.com/yiminghe/dom-align/blob/7548785a1b36b4813fa49b58c36bf419e8434c91/src/align/align.js#L110) 直接根据 `adjustX` 判断是否需要转向，因而 0 就被跳过了。绕了很远，直接 `adjustX` 默认 `1` 就能转了。
=> fix: auto dropdown placement

src/OptionList.tsx, tests/OptionList.test.tsx
This fixes [#33815](https://github.com/ant-design/ant-design/issues/33815)
=> Fix selecting an option with the keyboard while using fieldNames

src/OptionList.tsx, tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/34145﻿
=> fix: should display text properly if text is number 0

src/Selector/Input.tsx, tests/Select.test.tsx
resolve https://github.com/ant-design/ant-design/issues/33180
=> fix: clone input should not replace customize props

docs/examples/multiple.tsx, src/Select.tsx, tests/Multiple.test.tsx
- [ x ] 日常 bug 修复
https://codesandbox.io/s/laughing-fog-b12ijp?file=/src/App.js
当labelInValue=true mode=multiple的时候，value不在options内，删除会导致报错。
```
Select.tsx 447行：
const option = getMixedOption(val); // option可能为undefined,导致 option.key 抛出错误
```
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |
⚠️ 请自检并全部**勾选全部选项**。⚠️
=> feat: fix js error if value not in options

src/Select.tsx
resolve https://github.com/ant-design/ant-design/issues/34497
=> fix: onSelect & onDeSelect type

src/OptionList.tsx, tests/Group.test.tsx, tests/__snapshots__/Select.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
resolve https://github.com/ant-design/ant-design/issues/34496
=> fix: Group not provide title attr

README.md
This PR updates a `dropdownMatchSelectWidth` prop description typo on README.
=> fix(readme): update prop description typo

src/BaseSelect.tsx, src/SelectTrigger.tsx
This resolves https://github.com/react-component/select/issues/497
=> Fix: `dropdownAlign` type

src/BaseSelect.tsx, src/OptionList.tsx, tests/Select.test.tsx
* Change params of scrollTo from ScrollConfig to (number | ScrollConfig)
[issue-link](https://github.com/ant-design/ant-design/issues/34468)
=> Fix: fix scroll params

assets/index.less, src/OptionList.tsx, tests/Combobox.test.tsx
close https://github.com/ant-design/ant-design/issues/34975
AutoComplete 是输入模式，选中项只会干扰 active 样式，本身也没有实际交互意义。
=> feat: comobobox mode should not has selected item

src/OptionList.tsx, tests/Select.test.tsx, tests/__snapshots__/Select.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
resolve https://github.com/ant-design/ant-design/issues/35464
=> fix: No React warning for pass invalidate dom props

docs/examples/combobox.tsx, src/BaseSelect.tsx, src/Selector/Input.tsx, src/Selector/index.tsx, tests/Combobox.test.tsx
close https://github.com/ant-design/ant-design/issues/35913
=> fix: expose maxLength

src/OptionList.tsx, tests/Group.test.tsx
Previously the Group element showed some warnings regarding the title not being of type string for non-title type label values. This PR adds additional safeguards to avoid that.
fix https://github.com/ant-design/ant-design/issues/36005
=> fix: Group title warning

src/Selector/MultipleSelector.tsx, tests/Tags.test.tsx
fix https://github.com/ant-design/ant-design/issues/36112
=> fix: Multiple selector with customize tag not match the key of item

docs/examples/controlled.tsx, package.json, src/Select.tsx, src/utils/warningPropsUtil.ts, tests/Select.test.tsx
Changes:
1. add prettier latest (2.x) version to devDependencies, because the current prettier version added by 'umi-utils' is 1.x, which can't deal with typescript import type syntax (prettier 1.x error: SyntaxError: '=' expected).
2. add node children & options null value warning.
---
Chinese:
1. 添加了 prettier 的最新版本（2.x）到 devDependencies，因为当前由 'umi-utils' 安装的的 prettier 版本是 1.x, 不能正确处理 typescript 的 import type 语法（prettier 1.x 会报错：SyntaxError: '=' expected）。
2. 添加了 null 作为 option value 时的告警。
=> Add prettier latest version and option null value warning.

src/Selector/index.tsx
close https://github.com/ant-design/ant-design/issues/37320
=> fix: onMouseDown preventDefault when mode="combobox"

src/BaseSelect.tsx, src/Select.tsx, tests/shared/allowClearTest.tsx
fix [#33790](https://github.com/ant-design/ant-design/issues/33790)
=> fix: onClear triggers onDeselect in multiple mode

src/OptionList.tsx, tests/Multiple.test.tsx
close https://github.com/ant-design/ant-design/issues/38150
=> fix: Select should show selected icon when value is ''

assets/index.less
When Select animation is "slide-up" and placement is topLeft or topRight, rc-motion cannot trigger animationEnd event because animation-name is missing. cause Select error.
online demo: https://stackblitz.com/edit/react-ts-tcnr1w?file=App.tsx
related issues:
* https://github.com/react-component/select/issues/631
* https://github.com/react-component/select/issues/789
=> fix: Bugs caused by missing animation-name

src/Select.tsx, tests/type.test.tsx
[#34201](https://github.com/ant-design/ant-design/issues/34201#issuecomment-1308940256)
SelectHandler\<ValueType, OptionType extends BaseOptionType = DefaultOptionType\> = (
value: ValueType,
option: OptionType,
) => void;
onChange?: (value: ValueType, option: OptionType | OptionType[]) => void;
修复后，onselect类型定义和onchange的类型是相似的
=> fix: SelectHandler type fix

package.json, src/BaseSelect.tsx, tests/Combobox.test.tsx
`combo` 下内部 `open` 逻辑会有额外处理，这导致 blur 的时候发现 open 没开启就略过了设置 open 关闭。当有数据进入时就会被冲掉。
fix https://github.com/ant-design/ant-design/issues/38844
=> fix: should close when blur

docs/examples/custom-tags.tsx, package.json, src/OptionList.tsx, src/utils/valueUtil.ts
1. 'CustomTagProps' is removed in '../src/interface/generator';
2. '\<OptionList  ref={ref} /\>' ref:any can't distribute to ref:never
=> fix: tsc --noEmit error

package.json, src/OptionList.tsx, tests/OptionList.test.tsx, tests/__snapshots__/OptionList.test.tsx.snap
ref https://github.com/ant-design/ant-design/issues/39199
=> chore: Move option aria to real element when `virtual` is disabled

docs/examples/single.tsx, src/Selector/SingleSelector.tsx, tests/Combobox.test.tsx, tests/Select.test.tsx, tests/__snapshots__/Select.test.tsx.snap, tests/placeholder.test.tsx
close https://github.com/ant-design/ant-design/issues/27688
close https://github.com/ant-design/ant-design/issues/41530
Select 未选 item 时，此时进行搜，placeholder 会用 `visibility: hidden` 的方式隐藏，但是元素还在，承担了占位的作用。
Select 选了 item 后，原先的逻辑是 placeholder 元素直接 `return null`，因此没有占位了，整个 input 缩为 `0px`。
这里的逻辑改为：都使用 `visibility: hidden` 的方式隐藏 placeholder。当 Select 选了 item 后，placeholder 隐藏但文本内容改为 item 内容用于宽度占位。这样搜索时宽度不会变。
=> fix: Select width 0px when searching

package.json, src/Selector/SingleSelector.tsx, tests/Combobox.test.tsx, tests/__snapshots__/Select.test.tsx.snap, tests/placeholder.test.tsx
revert https://github.com/react-component/select/pull/934
换了一种方式修复。
=> fix: Select width became 0px when search after select something

package.json, src/OptionList.tsx, src/Select.tsx, src/SelectContext.ts, tests/Select.test.tsx, tests/__snapshots__/Select.test.tsx.snap, tests/__snapshots__/Tags.test.tsx.snap
- fix https://github.com/ant-design/ant-design/issues/42331
- fix https://github.com/react-component/virtual-list/pull/201
=> feat: add List ScrollBar direction

src/Select.tsx, tests/Select.test.tsx
* fix: Select label React Node warning some case
* test: test driven
* fix: warning of label when update
* chore: clean up
* chore: back of raw
---------
Co-authored-by: 洋 <hetongyang@bytedance.com>
Co-authored-by: 二货机器人 <smith3816@gmail.com>
(cherry picked from commit a5d4b7540e3953dbb3454bc00f1415bada9b0924)
#	src/Select.tsx
background: https://github.com/ant-design/ant-design/issues/43637#issuecomment-1641306585
=> fix: Select label React Node warning some case

src/Select.tsx, tests/Tags.test.tsx
close https://github.com/ant-design/ant-design/issues/43954
=> fix: ignore when search input value equal option item value

src/Selector/Input.tsx
close https://github.com/react-component/select/issues/978
=> #978 fix: initialise aria-expanded

src/BaseSelect.tsx, tests/focus.test.tsx
close https://github.com/ant-design/ant-design/issues/44619
问题出现原因：在 `Select` 触发 `onBlur` 后其 `disabled` 为 true 时触发了重置 focused 的操作，将 `onBlur` 要执行的回调给清除掉了。
=> fix: trigger onBlur does not require reset focused

docs/examples/custom-icon.tsx, src/OptionList.tsx, tests/Select.test.tsx
在我们项目的 UI 需求中，需要通过 option 的 `disabled` 和 `value` 来控制 icon 渲染，例如：
- 对于 disabled 的条目，需要展示一个 disabled 的 checkbox
- 对于特殊的 value，需要展示另一种 icon
- 否则，通过 `isSelected` 展示正常的 checkbox
目前 `menuItemSelectedIcon` 支持传入一个函数，但其中的参数只有一个 `{ isSelected: boolean }`，这个 PR 将 `value` 和 `disabled`添加进去，便于开发者使用。
如下图所示，第一条因为是 disabled 状态，所以右边的 icon 被设置为了 0.5 透明度。
- 行为一致：均为新增字段，因此之前的行为不会变
- 无需修改文档和类型：文档给的标注是 `(props: MenuItemProps) => ReactNode`，而 `MenuItemProps` 没有具体类型；ts 定义里面也没有固定类型
=> feat: add more props to TransBtn

docs/demo/scroll-loading.md, docs/examples/scroll-loading.tsx, src/OptionList.tsx
仅在 打开 和 搜索 变化时滚动到选中项，数据长度变化时不做滚动以防止动态 `options` 的场景导致的无限滚动。
resolves https://github.com/ant-design/ant-design/issues/45137 #982
=> chore: rm option len match

README.md, docs/demo/option-render.md, docs/examples/option-render.tsx, src/OptionList.tsx, src/Select.tsx, src/SelectContext.ts, tests/Select.test.tsx
close [#45445](https://github.com/ant-design/ant-design/issues/45445)
=> feat: Implement  `optionRender` API

src/Select.tsx, tests/Multiple.test.tsx
fix [#33790](https://github.com/ant-design/ant-design/issues/46476)
=> fix: incorrect display when value is null in multiple mode

docs/demo/auto-tokenization.md, docs/examples/auto-tokenization.tsx, src/BaseSelect.tsx, src/utils/valueUtil.ts
=> demo: update demo

src/BaseSelect.tsx
`maxCount` 只有在多选模式下才生效，虽然在 antd 里面做了一层判断，但是这里再判断一下，双保险，以防万一
=> chore: add multiple when onInternalSearch

src/SelectTrigger.tsx, tests/Popup.test.tsx, tests/SelectTrigger.spec.tsx, tests/Tags.test.tsx, tests/__mocks__/@rc-component/trigger.tsx
fix https://github.com/ant-design/ant-design/issues/48249
=> fix: Click Popup dom should not close the popup

src/Selector/index.tsx, tests/Combobox.test.tsx
【原因】
[issues 48281](https://github.com/ant-design/ant-design/issues/48281) 反馈 AutoComplete 点击边缘，下拉框会跳动，经过排查发现是因为 rc-select 在 mode 为 combobox 的时候，没有禁止默认行为，导致内部 Input 会不断的失焦和聚焦，下拉会不断的展开和隐藏。
在源码中注释了，combobox 没有阻止默认行为的原因是为解决 [issues 37320](https://github.com/ant-design/ant-design/issues/37320) 即 combobox 禁用状态下，无法选中文字的问题
为了同时解决上面的问题，并且不影响原来的其他逻辑，我添加了禁用状态的限制条件
=> fix: combobox prevent behavior

src/BaseSelect/Polite.tsx, src/BaseSelect/index.tsx, tests/BaseSelect.test.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/48833
之前以为是下拉框的性能问题，做了 diff 后发现没有关系。排查了一下：
=> fix: Chrome render perf issue

src/BaseSelect/index.tsx, src/SelectTrigger.tsx, tests/React.test.tsx
最好的解法是底层需要把相关组件都翻成 `nativeElement` 再通过 `rc-util/findDOMNode` 代理掉元素查询。不过工程略大，先在 Select 侧做一个兜底。
=> fix: React 18.3 warning

src/Select.tsx
This PR changes the type of `optionRender` to allow usage of a custom `OptionType`, rather than forcing `BaseOptionType`.
=> fix: fix typing of optionRender

src/BaseSelect/index.tsx, tests/Multiple.test.tsx, tests/Select.test.tsx, tests/utils/common.ts
https://github.com/ant-design/ant-design/issues/49941
=> feat: Prevent long press of enter

package.json, src/BaseSelect/index.tsx, src/Selector/MultipleSelector.tsx, src/interface.ts, tests/Tags.test.tsx
close https://github.com/ant-design/ant-design/issues/31501
=> feat: add parameter 'info' field 'index' to tagRender

src/Selector/MultipleSelector.tsx, tests/Tags.test.tsx
close https://github.com/ant-design/ant-design/issues/48930
=> fix: tagRender should not be called when value is empty for antd 5.x

src/Selector/Input.tsx, tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/53839
=> fix: simplify input props handling and improve accessibility features
