react-component/select

- src/Select.jsx
> Add className for placeholder

- src/Select.jsx
> do not hide menu when select a multiple or tag select

- assets/index.less
- package.json
- src/Select.jsx
antd 的动画。。。
rc-animate的key报错，，如果没key或null，能直接return child?
> Multiple anim

- src/Select.jsx
I want to capture the input keydown event, as I need to search items from back end when press enter, even no candidates.
> rc-select capture onInputKeyDown

- assets/index.less
- src/DropdownMenu.jsx
- src/Select.jsx
- src/SelectTrigger.jsx
- tests/Select.spec.js
https://github.com/ant-design/ant-design/issues/1390
> single search optimization

- package.json
- src/FilterMixin.js
> fix: `Select`'s children must be `Option` or `OptGorup`, close: #84

- assets/index.less
- src/Select.jsx
> fix search input width bug in IE 10/11

- assets/index.less
- examples/multiple-readonly.html
- examples/multiple-readonly.js
- src/Select.jsx
可以实现只读的预选项。
ant-design/ant-design#2034
> make disabled option can not be removed

- tests/Select.spec.js
> Add test case

- assets/index.less
- src/DropdownMenu.jsx
close ant-design/ant-design#3344
> Fix dropdown style when notFoundContent is empty

- examples/single.js
- src/Select.jsx
- close https://github.com/ant-design/ant-design/issues/3587
> add `onFocus` support

- examples/multiple.js
- examples/tags.js
- src/Select.jsx
- src/util.js
- tests/Select.spec.js
- tests/util.spec.js
https://github.com/ant-design/ant-design/issues/2071
https://github.com/react-component/select/issues/36
有个问题，因为 https://github.com/facebook/react/issues/3926 ，在 MacOS 的默认中文输入法输入的时候，输入法会自动在每个拼音字母中间加个空格，导致触发 tokenize，我暂时没有处理。
> Automatic tokenization

- src/Select.jsx
- tests/Select.spec.js
Fix https://github.com/ant-design/ant-design/issues/3401
> Display correct combobox label when it's under controllered

- src/Select.jsx
+ close https://github.com/ant-design/ant-design/issues/3778
+ reopen #129
+ close #129
> input of select could not focus

- README.md
- examples/multiple.js
- examples/single.js
- src/Select.jsx
Close: https://github.com/ant-design/ant-design/issues/3063
允许用户自定义 title。
> feat: customizable Option[title]

- src/Select.jsx
close ant-design/ant-design#4174
> Always sync input width when panel is open or not

- .travis.yml
- package.json
jest 17 在 node 7.4 下有用例会跑失败。
@yiminghe
> Upgrade jest

- src/DropdownMenu.jsx
- src/FilterMixin.js
- src/OptGroup.jsx
- src/Option.jsx
- src/Select.jsx
- src/util.js
- tests/FilterMixin.spec.js
https://github.com/ant-design/ant-design/issues/4655
为了兼容 react-hot-loader
> Use a special static property for type detecting

- src/Select.jsx
- tests/__snapshots__/Select.combobox.spec.js.snap
- tests/__snapshots__/Select.multiple.spec.js.snap
- tests/__snapshots__/Select.spec.js.snap
- tests/__snapshots__/Select.tags.spec.js.snap
Resolve the problem of text input jitter
https://github.com/ant-design/ant-design/issues/4992#issuecomment-281542159
> Fix issue https://github.com/ant-design/ant-design/issues/4992#issuecomment-281542159

- assets/index.less
- examples/multiple.js
- src/Select.jsx
ref: https://github.com/ant-design/ant-design/issues/4843
> feat: expose allowClear for Select[multiple|tags]

- src/FilterMixin.js
- tests/FilterMixin.spec.js
- tests/__snapshots__/FilterMixin.spec.js.snap
close ant-design/ant-design#5600
> Fix filterOption true bug

- src/Select.jsx
```jsx
<label htmlFor="xxx">click me</label>
<Select combobox id="xxx" />
```
写不了用例，enzyme 里没有 label 和 input 的关联效果。
> Add id for commbobox select

- examples/tags.js
- src/PropTypes.js
- src/Select.jsx
- tests/__snapshots__/Select.multiple.spec.js.snap
- tests/__snapshots__/Select.tags.spec.js.snap
- tests/shared/renderTest.js
Added tests and examples for PR #193. Contains @pindamonhangaba commits and missing tests. please reference original pr #193 for usage.
> Add limit to the amount of selected tags shown with tests

- examples/combobox.js
- src/PropTypes.js
- src/Select.jsx
- tests/Select.combobox.spec.js
- tests/Select.spec.js
- tests/shared/keyDownTest.js
Fixes https://github.com/ant-design/ant-design/issues/5942
> Add onInputKeyDown prop

- README.md
- examples/combobox.js
- examples/multiple.js
- examples/tags.js
- src/Select.jsx
- tests/Select.combobox.spec.js
- tests/Select.multiple.spec.js
- tests/Select.spec.js
- tests/Select.tags.spec.js
- tests/shared/dynamicChildrenTest.js
- tests/shared/removeSelectedTest.js
https://github.com/ant-design/ant-design/issues/9094
https://github.com/ant-design/ant-design/issues/4597
> Pass Option as onChange and onSelect second argument

- assets/index.less
> pointer-events: none applied to single select selected value

- src/Select.jsx
Fix https://github.com/ant-design/ant-design/issues/9510
> Prevent arrow click default behavior

- src/Select.jsx
- tests/shared/dynamicChildrenTest.js
fix https://github.com/ant-design/ant-design/issues/9445
> fix value label update bug when use defaultValue #269

- src/Select.jsx
- tests/shared/dynamicChildrenTest.js
Reverts react-component/select#270
> Revert "fix value label update bug when use defaultValue #269"

- examples/update-option.html
- examples/update-option.js
- tests/Select.combobox.spec.js
add a test case for avoid https://github.com/react-component/select/pull/273
add a demo for test option update
> add test case and demo

- src/Select.jsx
Same as `TreeSelect`: https://github.com/react-component/tree-select/pull/108/files
ref issue: https://github.com/ant-design/ant-design/issues/9849
> realign when input value changed

- src/Select.jsx
- tests/Select.multiple.spec.js
- tests/Select.spec.js
- tests/Select.tags.spec.js
- tests/shared/inputFilterTest.js
under multi mode, no need to clear input filter after menu select or deslect
> keep multiple filter

- assets/index.less
fix https://github.com/ant-design/ant-design/issues/10092
> Fix extra space taken up when arrow disabled

- src/Select.jsx
- tests/Select.multiple.spec.js
Same as TreeSelect: https://github.com/react-component/tree-select/pull/110
ref: https://github.com/ant-design/ant-design/issues/10274
> prevent popup when close click

- src/util.js
- tests/Select.multiple.spec.js
fix: https://github.com/ant-design/ant-design/issues/10440
> Fix error when has empty children

- README.md
`onInputKeydown` not work, but `onInputKeyDown` works like a charm.
> Fix documentation of onInputKeyDown method

- src/DropdownMenu.jsx
- src/Select.jsx
- src/SelectTrigger.jsx
- tests/__snapshots__/Select.tags.spec.js.snap
- tests/shared/focusTest.js
> reduce dom operation count

- src/DropdownMenu.jsx
- tests/DropdownMenu.spec.js
- tests/Select.spec.js
related issue with antd
https://github.com/ant-design/ant-design/issues/11170
> Autocomplete retaining old value

- examples/controlled.html
- examples/controlled.js
- src/Select.jsx
- tests/Select.spec.js
支持受控的 open
https://github.com/ant-design/ant-design/issues/10482
> support controlled open

- src/Select.jsx
- tests/Select.combobox.spec.js
- tests/Select.spec.js
- tests/Select.tags.spec.js
- tests/setup.js
- tests/shared/openControlledTest.js
use props.open when typeof props.open equals boolean
> make open controlled

- src/Select.jsx
closes https://github.com/ant-design/ant-design/issues/10506
> add support to activate when pressing Space

- examples/multiple.js
- src/Select.jsx
- tests/__snapshots__/Select.multiple.spec.js.snap
- tests/__snapshots__/Select.tags.spec.js.snap
- tests/shared/blurTest.js
fix https://github.com/ant-design/ant-design/issues/12281
> prevent focus blur event when click in multiple mode

- README.md
- examples/dropdownRender.html
- examples/dropdownRender.js
- src/PropTypes.js
- src/Select.jsx
- src/SelectTrigger.jsx
- tests/Select.spec.js
- tests/__snapshots__/Select.multiple.spec.js.snap
- tests/__snapshots__/Select.spec.js.snap
- tests/__snapshots__/Select.tags.spec.js.snap
--- UPDATE ---
use `dropdownRender` props to provide a full customization of dropdown menu
--------------
--- LEGACY ---
new feature props: 
- dropdownBeforeAddon
- dropdownAfterAddon
support both React.Node and render function
add an example HTML to test this feature
> :sparkles: dropdown render prop

- examples/optgroup.js
- src/Select.jsx
- tests/Select.optGroup.spec.js
ref: https://github.com/react-component/select/issues/321
> Option Group support filter

- src/Select.jsx
If you set or not tabIndex of "Select" component was 0. So now I added tabIndex prop to "rc-select".
> tabIndex prop added to rc-select

- .gitignore
- src/Select.tsx
- tests/Select.spec.tsx
- tests/__snapshots__/Select.combobox.spec.tsx.snap
- tests/__snapshots__/Select.multiple.spec.tsx.snap
- tests/__snapshots__/Select.spec.tsx.snap
- tests/__snapshots__/Select.tags.spec.tsx.snap
> new ariaId function

- src/Select.tsx
- tests/Select.combobox.spec.tsx
close ant-design/ant-design#10367
> Fix AutoComplete value when value is same as key

- README.md
- assets/index.less
- examples/multiple.js
- src/Select.tsx
- tests/Select.multiple.spec.tsx
Handle the multiple case by setting the showArrow to false by default if not set manually.
Fix : https://github.com/ant-design/ant-design/issues/12250
> Fix : Default showArrow value

- src/Select.tsx
- tests/Select.tags.spec.tsx
ref: https://github.com/ant-design/ant-design/issues/14090
> Support adding input value to options when filterOption exists

- src/Select.tsx
- src/util.ts
- tests/Select.spec.tsx
默认的 filterOption 把 disabled 的都阻止了  https://github.com/ant-design/ant-design/issues/14089
> Show disabled options

- examples/single.js
- src/Select.tsx
- tests/Select.spec.tsx
ref: https://github.com/ant-design/ant-design/issues/16223
Note: A minor version for this.
> fix: should trigger onSearch when search input changed

- src/Select.tsx
- tests/Select.spec.tsx
fix https://github.com/ant-design/ant-design/issues/17630
This should doc in antd changelog.
> fix: Adjust `onChange` & `onSelect` order

- package.json
Reverts react-component/select#414
> Revert "Update dom-scroll-into-view requirement from 1.x to 2.x"

- examples/single.tsx
- src/generate.tsx
- src/hooks/useSelectTriggerControl.ts
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/20266
> fix: Click outside should always trigger close

- package.json
- src/generate.tsx
- tests/Multiple.test.tsx
fix https://github.com/ant-design/ant-design/issues/20867
> fix: Backspace not update state

- src/generate.tsx
- tests/Select.test.tsx
fix https://github.com/react-component/select/issues/434
fix https://github.com/ant-design/ant-design/issues/20979
> fix: Select should reset when value change to `undefined`

- src/generate.tsx
- tests/Select.test.tsx
- tests/__snapshots__/Select.test.tsx.snap
fix https://github.com/ant-design/ant-design/issues/20999 for antd 4.x
> fix: ant-design/ant-design#20999 on master Close dropdown when select disabled

- src/generate.tsx
- tests/Select.test.tsx
fix: https://github.com/ant-design/ant-design/issues/21161
> fix: select reset logic

- src/DropdownMenu.tsx
- src/Select.tsx
- tests/Select.spec.tsx
- tests/__snapshots__/Select.spec.tsx.snap
fix https://github.com/ant-design/ant-design/issues/20999
> fix: ant-design/ant-design#20999 dropdown hiding issue when select disabled

- README.md
- examples/custom-tags.tsx
- src/Selector/MultipleSelector.tsx
- src/Selector/index.tsx
- src/generate.tsx
- src/interface/generator.ts
- tests/Tags.test.tsx
This is a PR to add custom renderer to rc-select.
This aims at addressing issues such as https://github.com/ant-design/ant-design/issues/12910
The aim would be to also support editing existing tags
> Adding a custom renderer for tags

- examples/single.less
- examples/single.tsx
- src/OptionList.tsx
- tests/Select.test.tsx
- tests/__snapshots__/Select.test.tsx.snap
ref: https://github.com/ant-design/ant-design/issues/21477
> fix: Option not pass className & style

- package.json
- src/Selector/index.tsx
- src/generate.tsx
- tests/Combobox.test.tsx
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/21662
> fix: Combobox click logic & open status

- .circleci/config.yml
- examples/single.tsx
- src/OptionList.tsx
- src/generate.tsx
- src/utils/commonUtil.ts
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/21796
> fix: `null` can be a value

- .prettierrc
- README.md
- package.json
- src/OptionList.tsx
- src/SelectTrigger.tsx
- src/generate.tsx
- tests/Select.test.tsx
- tests/__snapshots__/Select.test.tsx.snap
- tests/__snapshots__/Tags.test.tsx.snap
ref: https://github.com/ant-design/ant-design/issues/21722
> feat: dropdownMatchSelectWidth = false can disable virtual scroll

- package.json
- src/OptionList.tsx
- src/generate.tsx
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/22768
> chore: Reset scroll when search text changed

- README.md
- examples/single.tsx
- src/SelectTrigger.tsx
- src/generate.tsx
- tests/Select.test.tsx
- 增加 direction 可设置 RTL 
- RTL 模式下，dropdown 的默认方向应有 bottomLeft 调整为 bottomRight
https://github.com/ant-design/ant-design/issues/22580
> feat: add direction 

- examples/tags.tsx
- src/Selector/Input.tsx
- src/Selector/MultipleSelector.tsx
- src/Selector/SingleSelector.tsx
- src/Selector/index.tsx
- tests/Tags.test.tsx
resolve https://github.com/ant-design/ant-design/issues/23304
> chore: Support multiple line paste

- src/Selector/index.tsx
- tests/Multiple.test.tsx
fix https://github.com/ant-design/ant-design/issues/23262
> fix: Close popup should clean up input

- src/OptionList.tsx
- tests/OptionList.test.tsx
- tests/__snapshots__/Select.test.tsx.snap
- tests/__snapshots__/Tags.test.tsx.snap
ref https://github.com/ant-design/ant-design/issues/24331
> chore: auto aria-label

- src/Selector/index.tsx
close https://github.com/ant-design/ant-design/issues/24461
> fix: Select cannot paste

- src/generate.tsx
- src/hooks/useCacheOptions.ts
[#22822](https://github.com/ant-design/ant-design/issues/22822)
> chore: optimize multiple  onChange performence(#22822)

- src/generate.tsx
替换 Effect 更新为 rc-util 的 useMergedState 以减少 bundle size。
> chore: useMergeState

- src/Selector/index.tsx
- tests/Select.test.tsx
- tests/shared/blurTest.tsx
close https://github.com/ant-design/ant-design/issues/25354
原因很诡异，这里的 onClick 首次打开不触发。
> fix onFocus not trigger in IE11

- src/Selector/index.tsx
- src/generate.tsx
- tests/Tags.test.tsx
related issue:
https://github.com/ant-design/ant-design/issues/25642
> fix: separate error when content contains `\r\n`

- src/generate.tsx
- tests/Select.test.tsx
- tests/shared/allowClearTest.tsx
ref https://github.com/ant-design/ant-design/issues/21498
> feat: onClear

- src/utils/valueUtil.ts
- tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/26477
> fix: can search disabled item

- examples/single.tsx
https://select-git-fix-demo.react-component.vercel.app/iframe.html?id=rc-select--single
> docs: Not console everything

- src/utils/valueUtil.ts
- tests/Tags.test.tsx
resolve https://github.com/ant-design/ant-design/issues/27025
> fix: Options with same key

- package.json
- src/OptionList.tsx
resolve https://github.com/ant-design/ant-design/issues/27170
> chore: Show scrollbar when open

- examples/multiple.tsx
- src/Selector/MultipleSelector.tsx
- tests/Multiple.test.tsx
resolve https://github.com/ant-design/ant-design/issues/27999
> fix: MultipleSelect should inputable when first focus

- examples/custom-selector.tsx
- src/SelectTrigger.tsx
- src/generate.tsx
- tests/Select.test.tsx
- typings/index.d.ts
Used for `rc-cascader`. Do not use in your production.
> feat: Add getRawInputElement

- src/OptionList.tsx
resolve https://github.com/ant-design/ant-design/issues/33115
> chore: rm Object.values

- src/BaseSelect.tsx
- tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/33496
> fix: add onClick prop

- src/Select.tsx
- tests/Multiple.test.tsx
resolve https://github.com/ant-design/ant-design/issues/34048
> fix: no need warning when provide optionLabelProp

- src/Select.tsx
- src/hooks/useOptions.ts
- tests/Multiple.test.tsx
- tests/__snapshots__/Select.test.tsx.snap
- tests/__snapshots__/Tags.test.tsx.snap
close https://github.com/ant-design/ant-design/issues/35304
> fix: tokenSeparators should work when has optionFilterProp or optionLabelProp

- src/BaseSelect.tsx
- tests/BaseSelect.test.tsx
> fix: fix Select jump

- docs/examples/combobox.tsx
- src/Select.tsx
- src/utils/commonUtil.ts
- tests/Combobox.test.tsx
- tests/__snapshots__/Combobox.test.tsx.snap
https://github.com/react-component/select/pull/819#issuecomment-1233906778
> fix: trigger search value change when reset controlled combobox

- .eslintrc.js
- src/BaseSelect.tsx
- src/Select.tsx
- src/Selector/MultipleSelector.tsx
- src/Selector/SingleSelector.tsx
- src/utils/commonUtil.ts
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/37591
> fix: title in option not work

- src/BaseSelect.tsx
- src/Select.tsx
- src/Selector/MultipleSelector.tsx
- src/Selector/index.tsx
- tests/Multiple.test.tsx
fix: https://github.com/ant-design/ant-design/issues/38515
> fix: no display of searchValue when autoClearSearchValue is false

- docs/examples/multiple.tsx
- src/Selector/index.tsx
- tests/Multiple.test.tsx
fix: https://github.com/ant-design/ant-design/issues/38515
> fix: Don't clear searchValue onMouseDown when autoClearSearchValue is false

- src/BaseSelect.tsx
- tests/Select.test.tsx
fix https://github.com/ant-design/ant-design/issues/36048
> fix: when click clear button, it will be focused

- src/OptionList.tsx
close https://github.com/ant-design/ant-design/issues/40625
> feat(select): force scroll bar visible when list is changed

- src/BaseSelect.tsx
- src/Selector/SingleSelector.tsx
- src/Selector/index.tsx
- tests/Select.test.tsx
close https://github.com/ant-design/ant-design/issues/41247
> feat: support title

- src/Select.tsx
- tests/Select.test.tsx
- fix https://github.com/ant-design/ant-design/issues/40205#issuecomment-1574985576
> fix: Select label React Node warning some case

- package.json
> chore: bump rc-overflow

- src/BaseSelect.tsx
- tests/Select.test.tsx
fix: https://github.com/react-component/select/issues/960
> fix: use getBoundingClientRect to solve the width precision problem

- .github/workflows/main.yml
https://github.com/react-component/select/pull/961#issuecomment-1641858024
> ci: update CI workflow support for 14.1.x

- docs/examples/getPopupContainer.tsx
- src/BaseSelect.tsx
- src/SelectTrigger.tsx
- tests/__snapshots__/Select.test.tsx.snap
- tests/__snapshots__/Tags.test.tsx.snap
ref https://github.com/ant-design/ant-design/issues/44354
close #975
> refactor: Select use `@rc-component/trigger` align logic instead of self measure

- src/OptionList.tsx
- src/SelectTrigger.tsx
- src/Selector/Input.tsx
- src/Selector/SingleSelector.tsx
- src/Selector/index.tsx
给 displayName 添加 dev 环境，减少打包产物体积（可能吧）
> chore: add NODE_ENV to displayName

- src/BaseSelect.tsx
- src/Select.tsx
- src/Selector/MultipleSelector.tsx
- src/TransBtn.tsx
- src/hooks/useAllowClear.tsx
- src/interface.ts
> type: type lint-fix

- docs/examples/mul-suggest.tsx
- docs/examples/mul-tag-suggest.tsx
- docs/examples/multiple-readonly.tsx
- docs/examples/multiple.tsx
- src/BaseSelect.tsx
- src/OptionList.tsx
- src/Select.tsx
- src/Selector/Input.tsx
- src/Selector/MultipleSelector.tsx
- src/Selector/SingleSelector.tsx
> chore: code optimization

- src/hooks/useOptions.ts
> type: update type

- .gitignore
- README.md
- docs/examples/optgroup.tsx
- src/OptionList.tsx
- src/Select.tsx
add className / title ts type
add `group-option` custom className
> feat:  add option className/title type and feature

- .eslintrc.js
close https://github.com/react-component/select/security/code-scanning/1
> fix: code scanning alerts
